# Generated by Django 5.2.5 on 2025-08-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='station',
            new_name='bookmarked_station',
        ),
    ]
