# Generated by Django 5.2.6 on 2025-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_profile_image_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
