# Generated by Django 5.2.5 on 2025-09-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_price_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='fueltype',
            new_name='fuel_type',
        ),
    ]
