# Generated by Django 5.2.5 on 2025-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_rename_fueltype_price_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
