# Generated by Django 5.2.5 on 2025-09-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_price_last_updated'),
        ('stations', '0003_rename_stationid_station_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stations.station'),
        ),
    ]
