# Generated by Django 5.2.5 on 2025-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_alter_price_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
