# Generated by Django 5.2.5 on 2025-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_alter_price_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
