# Generated by Django 5.2.5 on 2025-08-31 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarks', '0002_rename_station_bookmark_bookmarked_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('record_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='bookmarks.bookmark')),
            ],
        ),
    ]
