# Generated by Django 5.2.5 on 2025-08-31 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_rename_station_bookmark_bookmarked_station'),
        ('price_records', '0002_pricerecords_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceRecords',
            new_name='PriceRecord',
        ),
    ]
