# Generated by Django 5.2.5 on 2025-09-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0003_rename_pricerecords_pricerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerecord',
            old_name='record_station',
            new_name='bookmark',
        ),
    ]
