# Generated by Django 5.2.5 on 2025-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0004_rename_record_station_pricerecord_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerecord',
            name='snapshot_price_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
