# Generated by Django 5.2.5 on 2025-09-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0005_pricerecord_snapshot_price_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerecord',
            name='snapshot_price',
        ),
    ]
