# Generated by Django 5.2.5 on 2025-09-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_records', '0006_remove_pricerecord_snapshot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerecord',
            old_name='snapshot_price_json',
            new_name='snapshot_price',
        ),
    ]
