# Generated by Django 5.2.5 on 2025-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='price',
        ),
        migrations.AddField(
            model_name='station',
            name='stationid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
