# Generated by Django 5.2.5 on 2025-09-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_station_price_station_stationid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='stationid',
            new_name='station_id',
        ),
    ]
