# Generated by Django 5.2.5 on 2025-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_rename_stationid_station_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
